# Generated by Django 5.0.1 on 2024-05-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transport_approval',
            fields=[
                ('bill_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vechical_no', models.CharField(max_length=100)),
                ('vechical_type', models.CharField(max_length=100)),
                ('fule_type', models.CharField(max_length=100)),
                ('driver_id', models.CharField(max_length=100)),
                ('buying_date', models.DateField()),
                ('overall_km', models.FloatField()),
                ('reason', models.CharField(max_length=500)),
                ('fuel_amount', models.IntegerField()),
                ('route', models.CharField(max_length=200)),
            ],
        ),
    ]
