# Generated by Django 5.0.1 on 2024-05-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_transport_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport_approval',
            name='buying_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport_approval',
            name='fuel_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport_approval',
            name='fule_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transport_approval',
            name='overall_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport_approval',
            name='reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transport_approval',
            name='route',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transport_approval',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transport_approval',
            name='vechical_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transport_approval',
            name='vechical_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
