# Generated by Django 5.0.1 on 2024-05-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_transport_approval_proof_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport_approval',
            name='distilled_water_quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transport_approval',
            name='engine_oil_quantity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transport_approval',
            name='grease_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transport_approval',
            name='grease_quantity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transport_approval',
            name='pdf_generrated_proof',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
