# Generated by Django 5.0.1 on 2024-05-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_transport_approval_distilled_water_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport_approval',
            old_name='pdf_generrated_proof',
            new_name='pdf_generated_proof',
        ),
    ]
