# Generated by Django 5.0.1 on 2024-05-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_rename_pdf_generrated_proof_transport_approval_pdf_generated_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport_approval',
            name='billed_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
