# Generated by Django 5.0.1 on 2024-05-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_transport_approval_billed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('conform_Password', models.CharField(max_length=100)),
            ],
        ),
    ]
