# Generated by Django 5.0.1 on 2024-05-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_master_vechicle_previous_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master_vechicle',
            old_name='Previous_us',
            new_name='Previous_km',
        ),
    ]
