# Generated by Django 5.0.1 on 2024-05-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_user_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport_approval',
            name='fuel_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
