# Generated by Django 5.0.6 on 2024-05-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_defalut_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport_approval',
            name='fuel_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
