# Generated by Django 5.0.1 on 2024-06-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_power_station_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='power_station_approval',
            name='fule_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
